### ISSUE TITLE
feature request: custom buffer size [ht16k33_alpha]

### ISSUE THREAD

**Issue by ShadyMCShadesen** [ssieb/esphome_components#26]
Hey,
it would be awesome if the ht16k33_alpha component supports a optional setting for the buffer size (default is 64, i had to display stuff that is long than this, so i increased it to 128 myself)

Something like this for example:
``` yaml
display:
  - platform: ht16k33_alpha
    address: 0x71
    buffer: 128 # <-- custom buffer setting (default to 64)
    scroll: true
    scroll_speed: 250ms
    scroll_dwell: 2s
    scroll_delay: 3
    lambda: |-
      it.print("HT16K33 Display Test");
    id: ${device_entity_id}_display
```
