### ISSUE TITLE
Could not find components folder for source.

### ISSUE THREAD

**Issue by SteveRMann** [ssieb/esphome_components#67]
**Never mind.**
It just started working, so I may have had a typo in my code.

I am trying to use an Adafruit HT16K33 with 14-segment LEDs.  When I put this at the top of my YAML code, I get the error in the title.

```
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/esphome_components
    components: [ ht16k33_alpha ]

```
However, when I go to the URL, there is clearly a components folder.
What am I doing wrong?
