### ISSUE TITLE
  [pin] is an invalid option for [binary_sensor.seesaw]

### ISSUE THREAD

**Issue by lboue** [ssieb/esphome_components#72]
Hello,

I am facing an issue when I try to configure seesaw componant for my [Adafruit I2C Quad Rotary Encoder Breakout with NeoPixel - STEMMA QT / Qwiic, Product ID: 5752]( https://www.adafruit.com/product/5752):
`  [pin] is an invalid option for [binary_sensor.seesaw].` This is for encoder switch.

These are the **pin names** in the seesaw firmware for each rotary encoder coming from : [Adafruit I2C Quad Rotary Encoder Breakout tutorial](https://learn.adafruit.com/adafruit-i2c-quad-rotary-encoder-breakout/circuitpython-and-python)
```
Encoder #0
  Switch: pin 12
  Encoder A: pin 8
  Encoder B: pin 9
Encoder #1
  Switch: pin 14
  Encoder A: pin 10
  Encoder B: pin 11
Encoder #2
  Switch: pin 17
  Encoder A: pin 2
  Encoder B: pin 3
Encoder #3
  Switch: pin 9
  Encoder A: pin 4
  Encoder B: pin 5
```

And this is **my config**:
```yaml
binary_sensor:
  - platform: seesaw
    id: button0
    pin: 12
    name: "Seesaw encoder button #0"

  - platform: seesaw
    id: button1
    pin: 14
    name: "Seesaw encoder button #1"

  - platform: seesaw
    id: button2
    pin: 17
    name: "Seesaw encoder button #2"

  - platform: seesaw
    id: button3
    pin: 9
    name: "Seesaw encoder button #3"

```

I am getting this **log when I build** this config:
```
INFO ESPHome 2024.3.2
INFO Reading configuration /config/esphome/adafruit-matrixportal-s3.yaml...
INFO Detected timezone 'Europe/Paris'
Failed config

binary_sensor.seesaw: [source /config/esphome/adafruit-matrixportal-s3.yaml:170]
  platform: seesaw
  id: button0
  
  [pin] is an invalid option for [binary_sensor.seesaw]. Please check the indentation.
  pin: 12
  name: Seesaw encoder button #0
```

Is there any way to correct this issue?

Regards
