### ISSUE TITLE
[pin] is an invalid option for [sensor.seesaw]  and type: encoder

### ISSUE THREAD

**Issue by lboue** [ssieb/esphome_components#73]
Hello,

I am facing an issue with seesaw componant and my [Adafruit I2C Quad Rotary Encoder Breakout with NeoPixel - STEMMA QT / Qwiic, Product ID: 5752]( https://www.adafruit.com/product/5752). Encoders count in the wrong direction.

So I try to configure seesaw componant and set pins to change the behavior but I got this error:
`  [pin] is an invalid option for [binary_sensor.seesaw].` This is for encoder switch.

These are the **pin names** in the seesaw firmware for each rotary encoder coming from : [Adafruit I2C Quad Rotary Encoder Breakout tutorial](https://learn.adafruit.com/adafruit-i2c-quad-rotary-encoder-breakout/circuitpython-and-python)
```
Encoder #0
  Switch: pin 12
  Encoder A: pin 8
  Encoder B: pin 9
Encoder #1
  Switch: pin 14
  Encoder A: pin 10
  Encoder B: pin 11
Encoder #2
  Switch: pin 17
  Encoder A: pin 2
  Encoder B: pin 3
Encoder #3
  Switch: pin 9
  Encoder A: pin 4
  Encoder B: pin 5
```

And this is **my config**:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
      ref: seesaw
    components: [ seesaw ]

sensor:
  - platform: seesaw
    id: encoder0
    type: encoder
    number: 0
    #pin: 8 --> [pin] is an invalid option for [sensor.seesaw]
    name: "Seesaw encoder #0"

  - platform: seesaw
    id: encoder1
    type: encoder
    number: 1
    #pin: 10
    name: "Seesaw encoder #1"

  - platform: seesaw
    id: encoder2
    type: encoder
    number: 2
    #pin: 2
    name: "Seesaw encoder #2"

  - platform: seesaw
    id: encoder3
    number: 3
    type: encoder
    #pin: 4
```

I am getting this **log when I build** this config:
```
INFO ESPHome 2024.4.0b3
...
Failed config

sensor.seesaw: [source /config/esphome/adafruit-matrixportal-s3.yaml:345]
  platform: seesaw
  id: encoder0
  type: encoder
  number: 0
  
  [pin] is an invalid option for [sensor.seesaw]. Please check the indentation.
  pin: 8
  name: Seesaw encoder #0
sensor.seesaw: [source /config/esphome/adafruit-matrixportal-s3.yaml:352]
  platform: seesaw
  id: encoder1
  type: encoder
  number: 1
  
  [pin] is an invalid option for [sensor.seesaw]. Please check the indentation.
  pin: 10
  name: Seesaw encoder #1
sensor.seesaw: [source /config/esphome/adafruit-matrixportal-s3.yaml:359]
  platform: seesaw
  id: encoder2
  type: encoder
  number: 2
  
  [pin] is an invalid option for [sensor.seesaw]. Please check the indentation.
  pin: 2
  name: Seesaw encoder #2
sensor.seesaw: [source /config/esphome/adafruit-matrixportal-s3.yaml:366]
  platform: seesaw
  id: encoder3
  number: 3
  type: encoder
  
  [pin] is an invalid option for [sensor.seesaw]. Please check the indentation.
  pin: 4
  name: Seesaw encoder #3

```

Is there any way to correct this issue?

Regards
