### ISSUE TITLE
Adafruit I2C Quad Rotary Encoder Breakout with NeoPixel / Seesaw Neopixel LED issue with 4 LED

### ISSUE THREAD

**Issue by lboue** [ssieb/esphome_components#74]
Hello,

I am facing an issue with seesaw componant and my [Adafruit I2C Quad Rotary Encoder Breakout with NeoPixel - STEMMA QT / Qwiic, Product ID: 5752](https://www.adafruit.com/product/5752). Encoders count in the wrong direction.

![adafruit_products_dbl](https://github.com/ssieb/esphome_components/assets/938089/7d6d1874-18f1-4a08-b1ef-ed47cf604ec8)

The LED on the first encoder works correctly, but the other 3 LEDs cannot be controlled.

I am using the `seesaw `branch of this github.

These are the **pin names** in the seesaw firmware for each rotary encoder coming from : [Adafruit I2C Quad Rotary Encoder Breakout tutorial](https://learn.adafruit.com/adafruit-i2c-quad-rotary-encoder-breakout/circuitpython-and-python)

```yaml
external_components:
  - source:
      type: git
      url: https://github.com/ssieb/custom_components
      ref: seesaw
    components: [ seesaw ]

light:
  - platform: seesaw
    id: pixel0
    pin: 18
    name: "Seesaw neopixel"
    #num_leds: 4

  - platform: seesaw
    id: pixel0
    pin: 18
    name: "Seesaw neopixel"
    #num_leds: 4
```

The `num_leds `parameter is not working:
```
Failed config

light.seesaw: [source /config/esphome/adafruit-matrixportal-s3.yaml:138]
  platform: seesaw
  id: pixel0
  pin: 18
  name: Seesaw neopixel
  
  [num_leds] is an invalid option for [light.seesaw]. Please check the indentation.
  num_leds: 4
```
