### ISSUE TITLE
[analog_keypad] `index: 0` is ambiguous

### ISSUE THREAD

**Issue by ptr727** [ssieb/esphome_components#80]
[Codegen](https://github.com/ssieb/esphome_components/blob/master/components/analog_keypad/binary_sensor/__init__.py#L30) for a `0` integer value in yaml results in ambiguity between [`const char *`](https://github.com/ssieb/esphome_components/blob/master/components/analog_keypad/binary_sensor/analog_keypad_binary_sensor.h#L11) and [`unit8_t`](https://github.com/ssieb/esphome_components/blob/master/components/analog_keypad/binary_sensor/analog_keypad_binary_sensor.h#L12) for `AnalogKeypadBinarySensor()`

```yaml
analog_keypad:
  sensor: adc_buttons
  debounce_time: 100
  keys:
    - voltage: 0.428571429
      variance: 0.1
    - voltage: 0.76744186
      variance: 0.1
    - voltage: 1.65
      variance: 0.1

binary_sensor:
  - platform: analog_keypad
    name: ${device_name}_button_up
    id: button_up
    index: 0
  - platform: analog_keypad
    name: ${device_name}_button_down
    id: button_down
    index: 1
  - platform: analog_keypad
    name: ${device_name}_button_enter
    id: button_enter
    index: 2
```

```console
Compiling .pioenvs/norvi-ae06r-test/src/main.o
src/main.cpp: In function 'void setup()':
src/main.cpp:274:60: error: call of overloaded 'AnalogKeypadBinarySensor(int)' is ambiguous
   button_up = new analog_keypad::AnalogKeypadBinarySensor(0);
                                                            ^
In file included from src/esphome.h:5,
                 from src/main.cpp:3:
src/esphome/components/analog_keypad/binary_sensor/analog_keypad_binary_sensor.h:12:3: note: candidate: 'esphome::analog_keypad::AnalogKeypadBinarySensor::AnalogKeypadBinarySensor(uint8_t)'
   AnalogKeypadBinarySensor(uint8_t index) : has_key_(false), index_(index){};
   ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/analog_keypad/binary_sensor/analog_keypad_binary_sensor.h:11:3: note: candidate: 'esphome::analog_keypad::AnalogKeypadBinarySensor::AnalogKeypadBinarySensor(const char*)'
   AnalogKeypadBinarySensor(const char *key) : has_key_(true), key_((uint8_t) key[0]){};
   ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/analog_keypad/binary_sensor/analog_keypad_binary_sensor.h:9:7: note: candidate: 'esphome::analog_keypad::AnalogKeypadBinarySensor::AnalogKeypadBinarySensor(const esphome::analog_keypad::AnalogKeypadBinarySensor&)'
 class AnalogKeypadBinarySensor : public AnalogKeypadListener, public binary_sensor::BinarySensor {
       ^~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/components/analog_keypad/binary_sensor/analog_keypad_binary_sensor.h:9:7: note: candidate: 'esphome::analog_keypad::AnalogKeypadBinarySensor::AnalogKeypadBinarySensor(esphome::analog_keypad::AnalogKeypadBinarySensor&&)'
*** [.pioenvs/norvi-ae06r-test/src/main.o] Error 1
========================= [FAILED] Took 16.25 seconds =========================
```
